services:
  - type: web
    name: innovation-hub-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server-production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_TYPE
        value: postgresql